version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        volumes:
            - ./:/var/www
        working_dir: /var/www
        ports:
            - "9000:9000"
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: social_network
            DB_USERNAME: laravel
            DB_PASSWORD: secret
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    vite:
        image: node:18-alpine
        container_name: laravel-vite
        working_dir: /var/www
        volumes:
            - ./:/var/www
        command: sh -c "npm install && npm run dev"
        ports:
            - "5173:5173"
        depends_on:
            - app

    db:
        image: postgres:15
        container_name: pgsql
        environment:
            POSTGRES_DB: social_network
            POSTGRES_USER: laravel
            POSTGRES_PASSWORD: secret
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@localhost.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - db

volumes:
    pgdata:
